zuul:
  routes:
    myProduct:
      path: /myProduct/**
      serviceId: product
#  ignored-patterns:
#    - /myProduct/product/listAllUp
  sensitive-headers:
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  redis:
    host: localhost
    port: 6379
    password: abcd1234
